create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  name text not null check (char_length(name) between 1 and 15),
  score integer not null check (score >= 0 and score <= 100000),
  level integer not null check (level in (1, 2, 3, 4, 5, 6, 7, 46)),
  game_duration_ms integer not null default 0 check (game_duration_ms >= 0),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create extension if not exists pgcrypto;

alter table public.scores
add column if not exists user_id uuid default auth.uid();

alter table public.scores
alter column user_id set default auth.uid();

alter table public.scores
add column if not exists game_duration_ms integer not null default 0;

alter table public.scores
add column if not exists updated_at timestamptz not null default now();

update public.scores
set user_id = gen_random_uuid()
where user_id is null;

alter table public.scores
alter column user_id set not null;

create unique index if not exists scores_user_id_key
on public.scores (user_id);

create index if not exists scores_score_created_at_idx
on public.scores (score desc, created_at asc);

alter table public.scores enable row level security;

revoke all on table public.scores from anon, authenticated;
grant select on public.scores to anon, authenticated;
grant insert, update on public.scores to authenticated;

revoke all on sequence public.scores_id_seq from anon, authenticated;
grant usage, select on sequence public.scores_id_seq to authenticated;

drop policy if exists "scores are public readable" on public.scores;
create policy "scores are public readable"
on public.scores
for select
to anon, authenticated
using (true);

drop policy if exists "players can submit scores" on public.scores;
create policy "players can submit scores"
on public.scores
for insert
to authenticated
with check (
  user_id = auth.uid()
  and char_length(name) between 1 and 15
  and score >= 0
  and score <= 100000
  and level in (1, 2, 3, 4, 5, 6, 7, 46)
  and game_duration_ms >= 0
);

drop policy if exists "players can update their score" on public.scores;
create policy "players can update their score"
on public.scores
for update
to authenticated
using (user_id = auth.uid())
with check (
  user_id = auth.uid()
  and char_length(name) between 1 and 15
  and score >= 0
  and score <= 100000
  and level in (1, 2, 3, 4, 5, 6, 7, 46)
  and game_duration_ms >= 0
);
