create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 15),
  score integer not null check (score >= 0 and score <= 100000),
  level integer not null check (level in (1, 2, 3, 4, 5, 6, 7, 46)),
  created_at timestamptz not null default now()
);

create index if not exists scores_top_idx
on public.scores (score desc, created_at asc);

alter table public.scores enable row level security;

grant select, insert on table public.scores to anon, authenticated;
grant usage, select on sequence public.scores_id_seq to anon, authenticated;

drop policy if exists "scores are public readable" on public.scores;
create policy "scores are public readable"
on public.scores
for select
to anon, authenticated
using (true);

drop policy if exists "players can submit scores" on public.scores;
create policy "players can submit scores"
on public.scores
for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 15
  and score >= 0
  and score <= 100000
  and level in (1, 2, 3, 4, 5, 6, 7, 46)
);
